version: "3.8" # docker 버전
services: # 사용할 서비스명 명시
  pharmacy-recommendation-redis: #서비스명
    container_name: pharmacy-recommendation-redis # 컨테이너명
    build:
      dockerfile: Dockerfile # Docker 파일의 이름
      context: ./redis # Docker 파일의 위치 (루트 디렉토리 redis디렉토리의 하위)
    image: mintaek/pharmacy-recommendation-redis # Docker 이미지의 이름 -- docker허브의 아이디가 먼저 명시되어야함. hub에 푸시할때 어떤 레포지토리로 해야할지 찾지 못하기 때문에 명시한다
    ports: # 포트포워딩
      - "6379:6379"
  pharmacy-recommendation-database:
    container_name: pharmacy-recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: mintaek/pharmacy-recommendation-database
    environment: # 환경변수 추가
      - MARIADB_DATABASE=pharmacy-recommendation # DB명
      - MARIADB_ROOT_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes: # db의 config 파일(한글 깨지지 말라고 추가한 것)을 참조해서 db 초기화를 할 수 있도록 참조
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"